[package]
name = "entropy_generator"
version = "0.1.0"
authors = ["Maxim Vinogradov <maxvinza@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tsdb = { path = "../libtsdb" }
sys-info = "0.5.8"
